# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
      exclude: 'requirements.txt|mlruns/|mlflow.db'
- repo: https://github.com/pycqa/isort
  rev: 5.13.2
  hooks:
    - id: isort
      name: isort (python)
      exclude: 'src/ml_workflow.py|monitoring/evidently_metrics_calculation.py|mlruns/|mlflow.db'
- repo: https://github.com/psf/black
  rev: 24.8.0
  hooks:
    - id: black
      language_version: python3.11
      exclude: 'src/ml_workflow.py|monitoring/evidently_metrics_calculation.py|mlrun/|mlflow.db'
- repo: local
  hooks:
    - id: pylint
      name: pylint
      entry: pylint
      language: system
      types: [python]
      args: [
        "-rn", # Only display messages
        "-sn", # Don't display the score
        "--recursive=y",
        "--rcfile=pyproject.toml" # Ensure pylint uses pyproject.toml
      ]
      exclude: 'mlruns/|mlflow.db'
