[tool.pylint.messages_control]

disable = [
    "missing-timeout",
    "missing-function-docstring",
    "import-error",
    "invalid-name",
    "missing-module-docstring",
    "not-callable",
    "wrong-import-position",
    "redefined-outer-name",
    "super-with-arguments",
    "unused-argument",
    "too-many-locals",
    "too-many-arguments",
    "duplicate-code",
    "line-too-long",
    "wrong-import-position",
    ]

[tool.black]
line-length = 88
target-version = ['py311']
skip-string-normalization = true

[tool.isort]
multi_line_output = 3
length_sort = false
